Added restart feature to UITestRunner
redhat-developer/intellij-common-ui-test-library pull request #166
Opened 2023-08-04 15:31 UTC by martinszuc

**Added restart feature to UITestRunner:**

**Reasons for this:**
- [Issue](https://github.com/redhat-developer/intellij-openshift-connector/issues/575)
- Restart required for successful login when no _/.kube/config_ is present. 
- Used in [intellij-openshift-connector](https://github.com/redhat-developer/intellij-openshift-connector) for IntegrationUITest

**Added:** 

- `restartIde(IntelliJVersion ideaVersion, int port)`
- `checkForMainIdeWindowOrWelcomeFrame()` for a little more control. If neither is found exception is thrown.

**Changed:** 

- Changed usage of `clearWorkspace()`  in the `runIde()` (clear IdeaProjects directory) to **optional**. Reason for this is that after restart of the IDE, the FlatWelcomeFrame does not necessarily  need to appear. For example when its restarted and the IDE automatically opens a already existing project that was created before restart. If the FlatWelcomeFrame is found, the workspace will still be cleared.
- Changed the `getRemoteRobotConnection(int port)` method so that its not looking for the FlatWelcomeFrame. Reason for this is the same. `getRemoteRobotConnection(int port)` only connects and returns instance of `RemoteRobot` and we verify existence of the FlatWelcomeFrame/MainIdeWindow elsewhere (line 92).

**Risks:** 

- I worry about timings when the program is waiting for some components to load during the `runIde()` and `restartIde()`.

2023-08-07 08:23 UTC, olkornii requested changes

2023-08-07 08:23 UTC, olkornii commented on src/main/java/com/redhat/devtools/intellij/commonuitest/UITestRunner.java
> +            checkForMainIdeWindowOrWelcomeFrame();
The name is a bit long. It would be great to make it a little shorter.

2023-08-07 08:23 UTC, olkornii commented on src/main/java/com/redhat/devtools/intellij/commonuitest/UITestRunner.java
> +            remoteRobot.find(FlatWelcomeFrame.class, Duration.ofSeconds(10));
Mb change duration to 60 seconds as it was. Need to try with Github Actions.

2023-08-24 08:02 UTC, olkornii approved these changes
LGTM

2023-10-11 16:53 UTC, lgrossma commented
Pretty nice feature, should be documented so people will know about this.

2024-02-12 17:19 UTC, closed without merging