fix: Update library for IJ 2023.2
redhat-developer/intellij-common-ui-test-library pull request #200
Opened 2023-11-07 13:19 UTC by martinszuc

This is PR aims to add IntelliJ IDEA 2023.2 to the library and fix issues found in epic: https://github.com/redhat-developer/intellij-common-ui-test-library/issues/187

2024-01-23 12:40 UTC, olkornii commented on src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/fixtures/test/dialogs/project_manipulation/NewProjectDialogTest.java
> +        assertTrue(currentlySelectedProjectSdk.contains("11"), "Selected project SDK should be Java 8 but is '" + currentlySelectedProjectSdk + "'");
Rewrite comments "Selected Project blablalba 8 ..." to "11".

2024-01-24 23:52 UTC, martinszuc commented on src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/dialogs/FlatWelcomeFrame.java
> +                return button(byXpath("//div[@defaulticon='createNewProjectTab.svg']"), Duration.ofSeconds(2));
whole thing was redundant

2024-01-24 23:52 UTC, martinszuc commented on src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/dialogs/FlatWelcomeFrame.java
> +            } catch (WaitForConditionTimeoutException e) {
whole thing was redundant

2024-01-24 23:52 UTC, martinszuc commented on src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/dialogs/FlatWelcomeFrame.java
> +                removeDialog.findText("Remove From List")
fixed

2024-02-08 13:06 UTC, olkornii requested changes

2024-02-08 13:06 UTC, olkornii commented on src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/fixtures/test/mainidewindow/toolwindowspane/ProjectExplorerTest.java
> +        SharedSteps.waitForComponentByXpath(remoteRobot,3,1, byXpath(XPathDefinitions.MY_ICON_LOCATE_SVG));
Try to verify "...3,1..." pause works.

2024-02-12 16:19 UTC, martinszuc commented on src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/dialogs/FlatWelcomeFrame.java
> +            if (ideaVersion >= 20223) {         //  COMMUNITY_V_2022_3 and higher version have different labels for Learn button
Fixed in open tip dialog commit. Also changed selectNewProjectTypeTest in same manner.

2024-02-13 12:01 UTC, lgrossma approved these changes

2024-02-13 15:37 UTC, merged